require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Acupuncture::ChannelsController do

  # This should return the minimal set of attributes required to create a valid
  # Acupuncture::Channel. As you add validations to Acupuncture::Channel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Acupuncture::ChannelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all acupuncture_channels as @acupuncture_channels" do
      channel = Acupuncture::Channel.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:acupuncture_channels)).to eq([channel])
    end
  end

  describe "GET show" do
    it "assigns the requested acupuncture_channel as @acupuncture_channel" do
      channel = Acupuncture::Channel.create! valid_attributes
      get :show, {:id => channel.to_param}, valid_session
      expect(assigns(:acupuncture_channel)).to eq(channel)
    end
  end

  describe "GET new" do
    it "assigns a new acupuncture_channel as @acupuncture_channel" do
      get :new, {}, valid_session
      expect(assigns(:acupuncture_channel)).to be_a_new(Acupuncture::Channel)
    end
  end

  describe "GET edit" do
    it "assigns the requested acupuncture_channel as @acupuncture_channel" do
      channel = Acupuncture::Channel.create! valid_attributes
      get :edit, {:id => channel.to_param}, valid_session
      expect(assigns(:acupuncture_channel)).to eq(channel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Acupuncture::Channel" do
        expect {
          post :create, {:acupuncture_channel => valid_attributes}, valid_session
        }.to change(Acupuncture::Channel, :count).by(1)
      end

      it "assigns a newly created acupuncture_channel as @acupuncture_channel" do
        post :create, {:acupuncture_channel => valid_attributes}, valid_session
        expect(assigns(:acupuncture_channel)).to be_a(Acupuncture::Channel)
        expect(assigns(:acupuncture_channel)).to be_persisted
      end

      it "redirects to the created acupuncture_channel" do
        post :create, {:acupuncture_channel => valid_attributes}, valid_session
        expect(response).to redirect_to(Acupuncture::Channel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved acupuncture_channel as @acupuncture_channel" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Acupuncture::Channel).to receive(:save).and_return(false)
        post :create, {:acupuncture_channel => { "name" => "invalid value" }}, valid_session
        expect(assigns(:acupuncture_channel)).to be_a_new(Acupuncture::Channel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Acupuncture::Channel).to receive(:save).and_return(false)
        post :create, {:acupuncture_channel => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested acupuncture_channel" do
        channel = Acupuncture::Channel.create! valid_attributes
        # Assuming there are no other acupuncture_channels in the database, this
        # specifies that the Acupuncture::Channel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Acupuncture::Channel).to receive(:update).with({ "name" => "MyString" })
        put :update, {:id => channel.to_param, :acupuncture_channel => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested acupuncture_channel as @acupuncture_channel" do
        channel = Acupuncture::Channel.create! valid_attributes
        put :update, {:id => channel.to_param, :acupuncture_channel => valid_attributes}, valid_session
        expect(assigns(:acupuncture_channel)).to eq(channel)
      end

      it "redirects to the acupuncture_channel" do
        channel = Acupuncture::Channel.create! valid_attributes
        put :update, {:id => channel.to_param, :acupuncture_channel => valid_attributes}, valid_session
        expect(response).to redirect_to(channel)
      end
    end

    describe "with invalid params" do
      it "assigns the acupuncture_channel as @acupuncture_channel" do
        channel = Acupuncture::Channel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Acupuncture::Channel).to receive(:save).and_return(false)
        put :update, {:id => channel.to_param, :acupuncture_channel => { "name" => "invalid value" }}, valid_session
        expect(assigns(:acupuncture_channel)).to eq(channel)
      end

      it "re-renders the 'edit' template" do
        channel = Acupuncture::Channel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Acupuncture::Channel).to receive(:save).and_return(false)
        put :update, {:id => channel.to_param, :acupuncture_channel => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested acupuncture_channel" do
      channel = Acupuncture::Channel.create! valid_attributes
      expect {
        delete :destroy, {:id => channel.to_param}, valid_session
      }.to change(Acupuncture::Channel, :count).by(-1)
    end

    it "redirects to the acupuncture_channels list" do
      channel = Acupuncture::Channel.create! valid_attributes
      delete :destroy, {:id => channel.to_param}, valid_session
      expect(response).to redirect_to(acupuncture_channels_url)
    end
  end

end
