require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Treatment::PointPrescriptionPointsController do

  # This should return the minimal set of attributes required to create a valid
  # Treatment::PointPrescriptionPoint. As you add validations to Treatment::PointPrescriptionPoint, be sure to
  # adjust the attributes here as well.
  let(:point_prescription) {create :treatment_point_prescription}
  let(:valid_attributes) { { "point_prescription_id" => point_prescription.id } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Treatment::PointPrescriptionPointsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all treatment_point_prescription_points as @treatment_point_prescription_points" do
      point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:treatment_point_prescription_points)).to eq([point_prescription_point])
    end
  end

  describe "GET show" do
    it "assigns the requested treatment_point_prescription_point as @treatment_point_prescription_point" do
      point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
      get :show, {:id => point_prescription_point.to_param}, valid_session
      expect(assigns(:treatment_point_prescription_point)).to eq(point_prescription_point)
    end
  end

  describe "GET new" do
    it "assigns a new treatment_point_prescription_point as @treatment_point_prescription_point" do
      get :new, {}, valid_session
      expect(assigns(:treatment_point_prescription_point)).to be_a_new(Treatment::PointPrescriptionPoint)
    end
  end

  describe "GET edit" do
    it "assigns the requested treatment_point_prescription_point as @treatment_point_prescription_point" do
      point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
      get :edit, {:id => point_prescription_point.to_param}, valid_session
      expect(assigns(:treatment_point_prescription_point)).to eq(point_prescription_point)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Treatment::PointPrescriptionPoint" do
        expect {
          post :create, {:treatment_point_prescription_point => valid_attributes}, valid_session
        }.to change(Treatment::PointPrescriptionPoint, :count).by(1)
      end

      it "assigns a newly created treatment_point_prescription_point as @treatment_point_prescription_point" do
        post :create, {:treatment_point_prescription_point => valid_attributes}, valid_session
        expect(assigns(:treatment_point_prescription_point)).to be_a(Treatment::PointPrescriptionPoint)
        expect(assigns(:treatment_point_prescription_point)).to be_persisted
      end

      it "redirects to the created treatment_point_prescription_point" do
        post :create, {:treatment_point_prescription_point => valid_attributes}, valid_session
        expect(response).to redirect_to(Treatment::PointPrescriptionPoint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved treatment_point_prescription_point as @treatment_point_prescription_point" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Treatment::PointPrescriptionPoint).to receive(:save).and_return(false)
        post :create, {:treatment_point_prescription_point => { "point_prescription_id" => "invalid value" }}, valid_session
        expect(assigns(:treatment_point_prescription_point)).to be_a_new(Treatment::PointPrescriptionPoint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Treatment::PointPrescriptionPoint).to receive(:save).and_return(false)
        post :create, {:treatment_point_prescription_point => { "point_prescription_id" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested treatment_point_prescription_point" do
        point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
        # Assuming there are no other treatment_point_prescription_points in the database, this
        # specifies that the Treatment::PointPrescriptionPoint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Treatment::PointPrescriptionPoint).to receive(:update).with({ "point_prescription_id" => "" })
        put :update, {:id => point_prescription_point.to_param, :treatment_point_prescription_point => { "point_prescription_id" => "" }}, valid_session
      end

      it "assigns the requested treatment_point_prescription_point as @treatment_point_prescription_point" do
        point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
        put :update, {:id => point_prescription_point.to_param, :treatment_point_prescription_point => valid_attributes}, valid_session
        expect(assigns(:treatment_point_prescription_point)).to eq(point_prescription_point)
      end

      it "redirects to the treatment_point_prescription_point" do
        point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
        put :update, {:id => point_prescription_point.to_param, :treatment_point_prescription_point => valid_attributes}, valid_session
        expect(response).to redirect_to(point_prescription_point)
      end
    end

    describe "with invalid params" do
      it "assigns the treatment_point_prescription_point as @treatment_point_prescription_point" do
        point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Treatment::PointPrescriptionPoint).to receive(:save).and_return(false)
        put :update, {:id => point_prescription_point.to_param, :treatment_point_prescription_point => { "point_prescription_id" => "invalid value" }}, valid_session
        expect(assigns(:treatment_point_prescription_point)).to eq(point_prescription_point)
      end

      it "re-renders the 'edit' template" do
        point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Treatment::PointPrescriptionPoint).to receive(:save).and_return(false)
        put :update, {:id => point_prescription_point.to_param, :treatment_point_prescription_point => { "point_prescription_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested treatment_point_prescription_point" do
      point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
      expect {
        delete :destroy, {:id => point_prescription_point.to_param}, valid_session
      }.to change(Treatment::PointPrescriptionPoint, :count).by(-1)
    end

    it "redirects to the treatment_point_prescription_points list" do
      point_prescription_point = Treatment::PointPrescriptionPoint.create! valid_attributes
      delete :destroy, {:id => point_prescription_point.to_param}, valid_session
      expect(response).to redirect_to(treatment_point_prescription_points_url)
    end
  end

end
