require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe References::TextbooksController do

  # This should return the minimal set of attributes required to create a valid
  # References::Textbook. As you add validations to References::Textbook, be sure to
  # adjust the attributes here as well.
  let(:author) { create :references_author }
  let(:valid_attributes) { { "author_id" => author.id } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # References::TextbooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all references_textbooks as @references_textbooks" do
      textbook = References::Textbook.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:references_textbooks)).to eq([textbook])
    end
  end

  describe "GET show" do
    it "assigns the requested references_textbook as @references_textbook" do
      textbook = References::Textbook.create! valid_attributes
      get :show, {:id => textbook.to_param}, valid_session
      expect(assigns(:references_textbook)).to eq(textbook)
    end
  end

  describe "GET new" do
    it "assigns a new references_textbook as @references_textbook" do
      get :new, {}, valid_session
      expect(assigns(:references_textbook)).to be_a_new(References::Textbook)
    end
  end

  describe "GET edit" do
    it "assigns the requested references_textbook as @references_textbook" do
      textbook = References::Textbook.create! valid_attributes
      get :edit, {:id => textbook.to_param}, valid_session
      expect(assigns(:references_textbook)).to eq(textbook)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new References::Textbook" do
        expect {
          post :create, {:references_textbook => valid_attributes}, valid_session
        }.to change(References::Textbook, :count).by(1)
      end

      it "assigns a newly created references_textbook as @references_textbook" do
        post :create, {:references_textbook => valid_attributes}, valid_session
        expect(assigns(:references_textbook)).to be_a(References::Textbook)
        expect(assigns(:references_textbook)).to be_persisted
      end

      it "redirects to the created references_textbook" do
        post :create, {:references_textbook => valid_attributes}, valid_session
        expect(response).to redirect_to(References::Textbook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved references_textbook as @references_textbook" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(References::Textbook).to receive(:save).and_return(false)
        post :create, {:references_textbook => { "author" => "invalid value" }}, valid_session
        expect(assigns(:references_textbook)).to be_a_new(References::Textbook)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(References::Textbook).to receive(:save).and_return(false)
        post :create, {:references_textbook => { "author" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested references_textbook" do
        textbook = References::Textbook.create! valid_attributes
        # Assuming there are no other references_textbooks in the database, this
        # specifies that the References::Textbook created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(References::Textbook).to receive(:update).with({ "author_id" => "" })
        put :update, {:id => textbook.to_param, :references_textbook => { "author_id" => "" }}, valid_session
      end

      it "assigns the requested references_textbook as @references_textbook" do
        textbook = References::Textbook.create! valid_attributes
        put :update, {:id => textbook.to_param, :references_textbook => valid_attributes}, valid_session
        expect(assigns(:references_textbook)).to eq(textbook)
      end

      it "redirects to the references_textbook" do
        textbook = References::Textbook.create! valid_attributes
        put :update, {:id => textbook.to_param, :references_textbook => valid_attributes}, valid_session
        expect(response).to redirect_to(textbook)
      end
    end

    describe "with invalid params" do
      it "assigns the references_textbook as @references_textbook" do
        textbook = References::Textbook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(References::Textbook).to receive(:save).and_return(false)
        put :update, {:id => textbook.to_param, :references_textbook => { "author" => "invalid value" }}, valid_session
        expect(assigns(:references_textbook)).to eq(textbook)
      end

      it "re-renders the 'edit' template" do
        textbook = References::Textbook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(References::Textbook).to receive(:save).and_return(false)
        put :update, {:id => textbook.to_param, :references_textbook => { "author" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested references_textbook" do
      textbook = References::Textbook.create! valid_attributes
      expect {
        delete :destroy, {:id => textbook.to_param}, valid_session
      }.to change(References::Textbook, :count).by(-1)
    end

    it "redirects to the references_textbooks list" do
      textbook = References::Textbook.create! valid_attributes
      delete :destroy, {:id => textbook.to_param}, valid_session
      expect(response).to redirect_to(references_textbooks_url)
    end
  end

end
