source 'https://rubygems.org'

# Specify your gem's dependencies in tcm_etl.gemspec
gem 'activesupport', '3.2.15'
platform :jruby do
  gem 'activerecord-jdbcpostgresql-adapter'
end

platform :ruby do
  gem 'pg'
end

gem 'activewarehouse-etl'
gem 'bcrypt-ruby'


gemspec
