
def import_formula(p, ch, cat, eng)
  f = Formula.search_equals(p)
  f = Formula.new(:pinyin=>p) unless f
  f.chinese = ch
  f.formula_category_list = cat
  f.english = eng

  if f.save
    puts "#{p}"
  else
    puts "NO SAVE: #{p}, #{ch}"
  end
end

FORMULA_NAMES = [['Zhi Zi Gan Jiang Tang', ' ', 'Clear Heat from the Qi Level', 'Gardenia and Ginger Decoction'],
['Bai Hu Cheng Qi Tang', '白虎承氣湯', 'Clear Heat from the Qi Level', 'White Tiger and Order the Qi Decoction'],
['Bai Hu Jia Cang Zhu Tang', ' ', 'Clear Heat from the Qi Level', 'White Tiger plus Atractylodis Decoction'],
['Bai Hu Jia Gui Zi Tang', '白虎加桂枝湯', 'Clear Heat from the Qi Level', 'White Tiger plus Cinnamon Twig Decoction'],
['Bai Hu Jia Ren Shen Tang', '白虎加人參湯', 'Clear Heat from the Qi Level', 'White Tiger plus Ginseng Decoction'],
['Bai Hu Tang', '白虎湯', 'Clear Heat from the Qi Level', 'White Tiger Decoction'],
['Chai Hu Bai Hu Tang', ' ', 'Clear Heat from the Qi Level', 'Bupleurum White Tiger Decoction'],
['Ling Xi Bai Hu Tang', ' ', 'Clear Heat from the Qi Level', 'White Tiger with Antelope and Rhinoceros'],
['Zhen Ni Bai Hu Tang', ' ', 'Clear Heat from the Qi Level', 'White Tiger Decoction to Suppress Rebellion'],
['Zhi Shi Zhi Zi Chi Tang', ' ', 'Clear Heat from the Qi Level', 'Bitter Orange, Gardenia, and Prepared Soybean Decoction'],
['Zhi Zi Da Huang Tang', ' ', 'Clear Heat from the Qi Level', 'Gardenia and Rhubarb Decoction'],
['Zhi Zi Dou Chi Tang', '梔子豆豉湯', 'Clear Heat from the Qi Level', 'Gardenia and Prepared Soybean Decoction'],
['Zhi Zi Gan Cao Chi Tang', ' ', 'Clear Heat from the Qi Level', 'Gardenia, Licorice, and Prepared Soybean Decoction'],
['Zhi Zi Hou Po Tang', ' ', 'Clear Heat from the Qi Level', 'Gardenia and Magnolia Bark Decoction'],
['Zhi Zi Sheng Jiang Chi Tang', ' ', 'Clear Heat from the Qi Level', 'Gardenia, Fresh Ginger, and Prepared Soybean Decoction'],
['Zhu Ye Shi Gao Tang', '竹葉石膏湯', 'Clear Heat from the Qi Level', 'Lophatherus and Gypsum Decoction'],
['Qing Ying Tang', '清營湯', 'Clear Heat from the Nutritive Level and Cool the Blood', 'Clear the Nutritive Level Decoction'],
['Shen Xi Dan', ' ', 'Clear Heat from the Nutritive Level and Cool the Blood', 'Magical Rhinoceros Special Pill'],
['Xi Jiao Di Huang Tang', '犀角地黃湯', 'Clear Heat from the Nutritive Level and Cool the Blood', 'Rhinoceros Horn and Rehmannia Decoction'],
['Fu Zi Xie Xin Tang', ' ', 'Clear Heat and Resolves Toxicity', 'Prepared aconite Decoction to Drain the Epigastrium'],
['Chong He Tang', ' ', 'Clear Heat and Resolves Toxicity', 'Flush and Harmonize Decoction'],
['Hua Ban Tang', ' ', 'Clear Heat and Resolves Toxicity', 'Transform Blotches Decoction'],
['Huang Lian Jie Du Tang', '黃蓮解毒湯', 'Clear Heat and Resolves Toxicity', 'Coptis Decoction to Relieve Toxicity'],
['Liu Shen Wan', '六神丸', 'Clear Heat and Resolves Toxicity', 'Six-Miracle Pill'],
['Nei Shu Huang Lian Tang', ' ', 'Clear Heat and Resolves Toxicity', 'Internal Dispersing Decoction with Coptis'],
['Niu Huang Shang Qing Wan', ' ', 'Clear Heat and Resolves Toxicity', 'Cattle Gallstone Pill to Ascend and Clear'],
['Pu Ji Xiao Du Yin', '普濟消毒飲', 'Clear Heat and Resolves Toxicity', 'Universal Benefit Decoction to Eliminate Toxin'],
['Qing Wen Bai Du Yin', '清瘟敗毒飲', 'Clear Heat and Resolves Toxicity', 'Clear Epidemics and Overcome Toxin Decoction'],
['Shen Xiao Tuo Li San', ' ', 'Clear Heat and Resolves Toxicity', 'Miraculous Powder for Supporting the Interior'],
['Si Miao Yong An Tang', '四妙勇安湯', 'Clear Heat and Resolves Toxicity', 'Four-Valiant Decoction for Well-being'],
['Wu Shen Tang', ' ', 'Clear Heat and Resolves Toxicity', 'Five Miracle Decoction'],
['Xiao Yan Jie Du Wan', ' ', 'Clear Heat and Resolves Toxicity', 'Reduce Inflammation and Relieve Toxicity Pill'],
['Xie Xin Tang', '瀉心湯', 'Clear Heat and Resolves Toxicity', 'Drain the Epigastrium Decoction'],
['Yin Hua Jie Du Tang', ' ', 'Clear Heat and Resolves Toxicity', 'Honeysuckle Decoction to Relieve Toxicity'],
['Bai Tou Weng Jia Gan Cao E Jiao Tang', '白頭翁加甘草阿膠湯', 'Clear Heat from the Organs', 'Pulsatilla Decoction plus Licorice and Ass-Hide Gelatin'],
['Bai Tou Weng Tang', '白頭翁湯', 'Clear Heat from the Organs', 'Pulsatilla Decoction'],
['Chai Hu Qing Gan Tang', ' ', 'Clear Heat from the Organs', 'Bupleurum Decoction to Clear the Liver'],
['Dang Gui Long Hui Wan', ' ', 'Clear Heat from the Organs', 'Tangkuei, Gentiana Longdancao, and Aloe Pill'],
['Dao Chi San', '導赤散', 'Clear Heat from the Organs', 'Guide Out the Red powder'],
['Jia Wei Bai Tou Weng Tang', ' ', 'Clear Heat from the Organs', 'Augmented Pulsatilla Decoction'],
['Long Dan Xie Gan Tang', '龍膽瀉肝湯', 'Clear Heat from the Organs', 'Gentiana Long Gan Cao Decoction to Drain the Liver'],
['Ma Xing Shi Gan Tang', '麻杏石甘湯', 'Clear Heat from the Organs', 'Ephedra, Apricot Kernel, Gypsum and Licorice Deco'],
['Qing Dan Xie Huo Tang', ' ', 'Clear Heat from the Organs', 'Clear the Gallbladder and Drain Fire Decoction'],
['Qing Wei San', '清胃散', 'Clear Heat from the Organs', 'Clear the Stomach powder'],
['Qing Wei Tang', ' ', 'Clear Heat from the Organs', 'Clear the Stomach Decoction'],
['Qing Xin Lian Zi Yin', '清心蓮子飲', 'Clear Heat from the Organs', 'Lotus Seed Decoction to Clear the Heart'],
['Sang Dan Xie Bai Tang', ' ', 'Clear Heat from the Organs', 'Mulberry Leaf and Moutan Decoction to Drain the White'],
['Ting Li Da Zao Xie Fei Tang', ' ', 'Clear Heat from the Organs', 'Descurainia and Jujube Decoction'],
['Wei Jing Tang', '葦莖湯', 'Clear Heat from the Organs', 'Reed Decoction'],
['Wu Hu Tang', ' ', 'Clear Heat from the Organs', 'Five Tiger Decoction'],
['Wu Ji Wan', ' ', 'Clear Heat from the Organs', 'Fifth and Sixth Heavenly Stem Pill'],
['Xiang Lian Wan', ' ', 'Clear Heat from the Organs', 'Aucklandia and Coptis Pill'],
['Xie Bai San', '瀉白散', 'Clear Heat from the Organs', 'Drain the White powder'],
['Xie Huang San', '瀉黃散', 'Clear Heat from the Organs', 'Drain the Yellow Powder'],
['Xie Qing Wan', ' ', 'Clear Heat from the Organs', 'Drain the Green Pill'],
['Xie Xin Dao Chi Tang', ' ', 'Clear Heat from the Organs', 'Drain the Epigastrium and Guide Out the Red Decoction'],
['Yin Qiao Ma Bo San', '銀翹馬勃散', 'Clear Heat from the Organs', 'Honeysuckle, Forsythia and Puff Ball Powder'],
['Yu Nu Jian', '玉女煎', 'Clear Heat from the Organs', 'Jade Woman Decoction'],
['Yue Bi Jia Zhu Tang', ' ', 'Clear Heat from the Organs', 'Maidservant from Yue Decoction Plus Atractylodes'],
['Yue Bi Tang', ' ', 'Clear Heat from the Organs', 'Maidservant from Yue Decoction'],
['Zuo Jin Wan', '左金丸', 'Clear Heat from the Organs', 'Left Metal pill'],
['Di Gu Pi Yin', ' ', 'Clear Heat from Deficiency', 'Lycium Root Bark Decoction'],
['Qin Jiao Bie Jia San', ' ', 'Clear Heat from Deficiency', 'Gentiana Qinjiao and Soft-Shelled Turtle Shell Powder'],
['Qing Gu San', '清骨散', 'Clear Heat from Deficiency', 'Cool the Bones Powder'],
['Qing Hao Bie Jia Tang', '青蒿鱉甲湯', 'Clear Heat from Deficiency', 'Artemisia Annua and Soft-Shelled Turtle Shell Deco'],
['Qing Jing San', ' ', 'Clear Heat from Deficiency', 'Clear the Menses Powder'],
['Ren Shen Huang Qi San', ' ', 'Clear Heat from Deficiency', 'Ginseng and Astragalus Powder'],
['Ji Su San', ' ', 'Relieve Summerheat', 'Peppermint Powder'],
['Li Shi Qing Shu Yi Qi Tang', ' ', 'Relieve Summerheat', 'Master Li\'s Decoction to clear Summerheat and Augment the Qi'],
['Bi Yu San', '碧玉散', 'Relieve Summerheat', 'Jasper Powder'],
['Gui Ling Gan Lu Yin', '桂苓甘露飲', 'Relieve Summerheat', 'Cinnamon and Poria Sweet Dew Decoction'],
['Lei Shi Qing Liang Di Shu Tang', ' ', 'Relieve Summerheat', 'Master Lei\'s Decoction to Clear, Cool and Remove Summerheat'],
['Liu Yi San', '六一散', 'Relieve Summerheat', 'Six to One Powder'],
['Qing Luo Yin', '清絡飲', 'Relieve Summerheat', 'Clear the Collaterals Decoction'],
['Qing Shu Yi Qi Tang', '清暑益氣湯', 'Relieve Summerheat', 'Clear Summer-heat and Augment the Qi Decoction'],
['Yi Yuan San', ' ', 'Relieve Summerheat', 'Benefit the Basal Powder'],
['Da Cheng Qi Tang', '大承氣湯', 'Purge Heat Accumulation', 'Major Order the Qi Decoction'],
['Da Huang Gan Cao Tang', '大黃甘草湯', 'Purge Heat Accumulation', 'Rhubard and Licorice Decoction'],
['Da Huang Mu Dan Tang', '大黃牡丹湯', 'Purge Heat Accumulation', 'Rhubarb and Moutan Decoction'],
['Da Xian Xiong Tang', '大陷胸湯', 'Purge Heat Accumulation', 'Major Sinking into the Chest Decoction'],
['Da Xian Xiong Wan', '大陷胸丸', 'Purge Heat Accumulation', 'Major Sinking Into the Chest Pill'],
['Fu Fang Da Cheng Qi Tang', '複方大承氣湯', 'Purge Heat Accumulation', 'Revised Major Order the Qi Decoction'],
['Geng Yi Wan', ' ', 'Purge Heat Accumulation', 'Pill Requiring a Change of Clothes'],
['Hou Po San Wu Tang', ' ', 'Purge Heat Accumulation', 'Three Substance Decoction with Magnolia Bark'],
['Huang Long Tang', '黃龍湯', 'Purge Heat Accumulation', 'Yellow Dragon Decoction'],
['Liang Ge San', '涼膈散', 'Purge Heat Accumulation', 'Cool the Diaphragm Powder'],
['Qing Xin Liang Ge San', ' ', 'Purge Heat Accumulation', 'Clear the Heart and Cool the Diaphragm Powder'],
['Tiao Wei Cheng Qi Tang', '調胃承氣湯', 'Purge Heat Accumulation', 'Regulate the Stomach and Order the Qi Decoction'],
['Xiao Cheng Qi tang', '小承氣湯', 'Purge Heat Accumulation', 'Minor Order the Qi Decoction'],
['Xin Jia Huang Long Tang', '新加黃龍湯', 'Purge Heat Accumulation', 'Newly-Augmented Yellow Dragon Decoction'],
['Yi Yi Fu Zi Bai Jiang San', ' ', 'Purge Heat Accumulation', 'Cocis, Prepared Aconite and Baijiangcao Powder'],
['Zeng Ye Cheng Qi Tang', '增液承氣湯', 'Purge Heat Accumulation', 'Increases the fluids and Order the Qi Decoction'],
['Bai San', ' ', 'Drain Downward', 'White Powder'],
['Da Cheng Qi Tang', '大承氣湯', 'Drain Downward', 'Major Order the Qi Decoction'],
['Da Huang Fu Zi Tang', '大黃附子湯', 'Drain Downward', 'Rhubarb and Prepared Aconite Decoction'],
['Da Huang Gan Cao Tang', '大黃甘草湯', 'Drain Downward', 'Rhubard and Licorice Decoction'],
['Da Huang Mu Dan Tang', '大黃牡丹湯', 'Drain Downward', 'Rhubarb and Moutan Decoction'],
['Da Xian Xiong Tang', '大陷胸湯', 'Drain Downward', 'Major Sinking into the Chest Decoction'],
['Da Xian Xiong Wan', '大陷胸丸', 'Drain Downward', 'Major Sinking Into the Chest Pill'],
['Fu Fang Da Cheng Qi Tang', '複方大承氣湯', 'Drain Downward', 'Revised Major Order the Qi Decoction'],
['Geng Yi Wan', ' ', 'Drain Downward', 'Pill Requiring a Change of Clothes'],
['Hou Po San Wu Tang', ' ', 'Drain Downward', 'Three Substance Decoction with Magnolia Bark'],
['Huang Long Tang', '黃龍湯', 'Drain Downward', 'Yellow Dragon Decoction'],
['Ji Chuan Jian', '濟川煎', 'Drain Downward', 'Benefit the River (Flow], Decoction'],
['Ji Jiao Li Huang Wan', '己椒藶黃丸', 'Drain Downward', 'Stephania, Zanthoxylum, Descurainia, and Rhubard Pill'],
['Kong Xian Dan', '控涎丹', 'Drain Downward', 'Control Mucus Special Pill'],
['Liang Ge San', '涼膈散', 'Drain Downward', 'Cool the Diaphragm Powder'],
['Ma Zi Ren Wan', '麻子仁丸', 'Drain Downward', 'Hemp Seed Pill'],
['Qing Xin Liang Ge San', ' ', 'Drain Downward', 'Clear the Heart and Cool the Diaphragm Powder'],
['Run Chang Wan', '潤腸丸', 'Drain Downward', 'Moisten the Intestines Pill (from Master Shen\'s Bo'],
['San Wu Bei Ji Wan', '三物備急丸', 'Drain Downward', 'Three-Substance pill for Emergencies'],
['Shi Zao Tang', '十棗湯', 'Drain Downward', 'Ten-Jujube Decoction'],
['Tiao Wei Cheng Qi Tang', '調胃承氣湯', 'Drain Downward', 'Regulate the Stomach and Order the Qi Decoction'],
['Wen Pi Tang', '溫脾湯', 'Drain Downward', 'Warm the Spleen Decoction'],
['Wu Ren Wan', '五仁丸', 'Drain Downward', 'Five-Seed Pill'],
['Xiao Cheng Qi tang', '小承氣湯', 'Drain Downward', 'Minor Order the Qi Decoction'],
['Xin Jia Huang Long Tang', '新加黃龍湯', 'Drain Downward', 'Newly-Augmented Yellow Dragon Decoction'],
['Yi Yi Fu Zi Bai Jiang San', ' ', 'Drain Downward', 'Cocis, Prepared Aconite and Baijiangcao Powder'],
['Zeng Ye Cheng Qi Tang', '增液承氣湯', 'Drain Downward', 'Increases the fluids and Order the Qi Decoction'],
['Zhou Che Wan', '舟車丸', 'Drain Downward', 'Vessel and Vehicle Pill'],
['Bai Zi Yang Xin Wan', '柏子養心湯', 'Calm the Spirit ', 'Biota Seed Pill to Nourish the Heart'],
['Chai Hu Jia Long Gu Mu Li Tang', '柴胡加龍骨牡蠣湯', 'Calm the Spirit ', 'Bupleurum plus Dragon Bone and Oyster Shell Decoction'],
['Ci Zhu Wan', '磁朱丸', 'Calm the Spirit ', 'Magnetite and Cinnabar Pill'],
['Ding Zhi Wan', '定志丸', 'Calm the Spirit ', 'Settle the Emotions Pill'],
['Ding Zhi Wan modified', ' ', 'Calm the Spirit ', 'Settle the Emotions Pill from the Wondrous Lantern'],
['Gan Mai Da Zao Tang', '甘麥大棗湯', 'Calm the Spirit ', 'Licorice Wheat and Jujube Decoction'],
['Huang Lian E Jiao Tang', '黃蓮阿膠湯', 'Calm the Spirit ', 'Coptis and Ass- Hide Gelatin Decoction'],
['Jiao Tai Wan', ' ', 'Calm the Spirit ', 'Grand Communication Pill'],
['Miao Xiang San', '妙香散', 'Calm the Spirit ', 'Marvelously Fragrant Powder'],
['Sheng Tie Lou Yin', '生鐵落飲', 'Calm the Spirit ', 'Iron Filings Decoction'],
['Suan Zao Ren Tang', '酸棗仁湯', 'Calm the Spirit ', 'Sour Jujube Decoction'],
['Tian Wang Bu Xin Dan', '天王補心丹', 'Calm the Spirit ', 'Emperor of Heaven\'s Special Pill to Tonify the Heart'],
['Yang Xin Tang', '養心湯', 'Calm the Spirit ', 'Nourish the Heart Decoction'],
['Zhen Zhu Mu Wan', '珍珠母丸', 'Calm the Spirit ', 'Mother of Pearl Pill'],
['Zhu Sha An Shen Wan', '朱砂安神丸', 'Calm the Spirit ', 'Cinnabar Pill to Calm the Spirit'],
['Dang Gui Nian Tong Tang', '當歸拈痛湯', 'Expel Dampness', ' '],
['Ba Zheng San', '八正散', 'Expel Dampness', 'Eight Herb Powder for Rectification'],
['Bi Xie Fen Qing Yin', '萆薢分清飲', 'Expel Dampness', 'Dioscorea Hypoglauca Decoction to Separate the Clear'],
['Bu Huan Jin Zheng Qi San', '不換金正氣散', 'Expel Dampness', 'Rectify the Qi Powder Worth More than Gold'],
['Chu Shi Wei Ling Tang', '除濕胃苓湯', 'Expel Dampness', 'Eliminate Dampness Decoction by Combining Calm the Stomach and Five-Ingredient Powder with Poria'],
['Chun Ze Tang', '春澤湯', 'Expel Dampness', 'Spring Pond Decoction'],
['Da Fang Feng Tang', '大防風湯', 'Expel Dampness', 'Major Ledebouriella Decoction'],
['Da Qin Jiao Tang', '大秦艽湯', 'Expel Dampness', 'Major Gentiana Qinjiao Decoction'],
['Du Huo Ji Sheng Tang', '獨活寄生湯', 'Expel Dampness', 'Angelica Pubescens and Sang-Ji-Sheng Decoction'],
['Er Jia Jian Zheng Qi San', '二加減正氣散', 'Expel Dampness', 'Second Modification of Rectify the Qi Powder'],
['Er Miao San', '二妙散', 'Expel Dampness', 'Two Marvel Powder'],
['Fang Ji Fu Ling Tang', '防己茯苓湯', 'Expel Dampness', 'Stephania and Poria Decoction'],
['Fang Ji Huang Qi Tang', '防己黃耆湯', 'Expel Dampness', 'Stephania and Astragalus Decoction'],
['Fen Xiao Tang', '分消湯', 'Expel Dampness', 'Separate and Reduce Decoction'],
['Fu Zi Tang', '附子湯', 'Expel Dampness', 'Prepared Aconite Decoction'],
['Gan Lu Xiao Du Dan', '甘露消毒丹', 'Expel Dampness', 'Sweet Dew Special Pill to Eliminate Toxin'],
['Gui Zhi Shao Yao Zhi Mu Tang', '桂枝芍藥知母湯', 'Expel Dampness', 'Cinnamon Twig, Peony, and Anemarrhena Decoction'],
['Huang Qin Hua Shi Tang', '黃芩化濕湯', 'Expel Dampness', 'Scutellaria and Talcum Decoction'],
['Huang Qin Tang', '黃芩湯', 'Expel Dampness', 'Scutellaria Decoction'],
['Huo Po Xia Ling Tang', '厚朴夏苓湯', 'Expel Dampness', 'Agastache, Magnolia Bark, Pinellia and Poria Decoction'],
['Huo Xiang Zheng Qi San', '藿香正氣散', 'Expel Dampness', 'Agastache powder to Rectify the Qi'],
['Ji Ming San', '雞鳴散', 'Expel Dampness', 'Powder to Take at Cock\'s Crow'],
['Jia Wei Er Miao Wan', '加味二妙丸', 'Expel Dampness', 'Augmented Two-Marvel Pill'],
['Jia Wei Wu Lin San', '加味五淋散', 'Expel Dampness', 'Augmented Five-Ingredient Powder for Painful Urinary Dysfunction'],
['Juan Bi Tang', '蠲痺湯', 'Expel Dampness', 'Remove Painful Obstruction Decoction'],
['Lian Po Yin', '蓮朴飲', 'Expel Dampness', 'Coptis and Magnolia Bark Decoction'],
['Liu He Tang', '六合湯', 'Expel Dampness', 'Harmonize the Six Decoction'],
['Ping Wei San', '平胃散', 'Expel Dampness', 'Calm the Stomach Powder'],
['Qi Pi Yin', '七皮飲', 'Expel Dampness', 'Seven-Peel Decoction'],
['Qiang Huo Sheng Shi Tang', '羌活勝濕湯', 'Expel Dampness', 'Notopterygium Decoction to Overcome Dampness'],
['San Bi Tang', '三痺湯', 'Expel Dampness', 'Three Painful Obstruction Decoction'],
['San Jia Jian Zheng Qi San', '三加減正氣散', 'Expel Dampness', 'Third Modification of Rectify the Qi Powder'],
['San Jin Tang', '三金湯', 'Expel Dampness', 'Three-Gold Decoction'],
['San Miao Wan', '三妙丸', 'Expel Dampness', 'Three-Marvel Pill'],
['San Ren Tang', '三仁湯', 'Expel Dampness', 'Three Nut Decoction'],
['Shao Yao Tang', '芍藥湯', 'Expel Dampness', 'Peony Decoction'],
['Shen Shi Zhu Ling Tang', '沈石豬苓湯', 'Expel Dampness', 'Polyporus Decoction from Master Shen'],
['Shi Pi Yin', '實脾飲', 'Expel Dampness', 'Bolster the Spleen Decoction'],
['Shu Feng Huo Xue Tang', '疏風活血湯', 'Expel Dampness', 'Disperse Wind and Invigorate Blood Decoction'],
['Si Jia Jian Zheng Qi San', '四加減正氣散', 'Expel Dampness', 'Fourth Modification of Rectify the Qi Powder'],
['Si Ling San', '四苓散', 'Expel Dampness', 'Four Ingredient Powder with Poria'],
['Si Miao Wan', '四妙丸', 'Expel Dampness', 'Four-Marvel Pill'],
['Wei Ling Tang', '胃苓湯', 'Expel Dampness', 'Calm the Stomach and Poria Decoction'],
['Wu Jia Jian Zheng Qi San', '五加減正氣散', 'Expel Dampness', 'Fifth Modification of Rectify the Qi Powder'],
['Wu Lin San', '五淋散', 'Expel Dampness', 'Five-Ingredient Powder for Painful Urinary Dysfunction'],
['Wu Ling San', '五苓散', 'Expel Dampness', 'Five-Ingredient Powder with Poria'],
['Wu Pi San', '五皮散', 'Expel Dampness', 'Five Peel powder'],
['Wu Pi Yin', '五皮飲', 'Expel Dampness', 'Five Peel Decoction'],
['Xiang Sha Ping Wei San', '香砂平胃散', 'Expel Dampness', 'Cyperus and Amomum Powder to Calm the Stomach'],
['Xing Ren Hua Shi Tang', '杏仁滑石湯', 'Expel Dampness', 'Apricot Kernel and Talcum Decoction'],
['Xuan Bi Tang', '宣痺湯', 'Expel Dampness', 'Disband Painful Obstruction Decoction'],
['Yi Jia Jian Zheng Qi San', '一加減正氣散', 'Expel Dampness', 'First Modification of Rectify the Qi Powder'],
['Yi Yi Ren Tang', '薏苡仁湯', 'Expel Dampness', 'Coicis Decoction from the Enlightened Physicians'],
['Yin Chen Hao Tang', '茵陳蒿湯', 'Expel Dampness', 'Artemisia Yinchenhao Decoction'],
['Yin Chen Si Ni Tang', '茵陳四逆湯', 'Expel Dampness', 'Artemisia Yinchenhao Decoction for Frigid Extremities'],
['Yin Chen Wu Ling San', '茵陳五苓散', 'Expel Dampness', 'Artemisia Yinchenhao and Five-Ingredient Powder with Poria'],
['Yin Chen Zhu Fu Tang', '茵陳朮附湯', 'Expel Dampness', 'Artemisia Yinchenhao, Atractylodes and Prepared Aconite Decoction'],
['Yu Dai Wan', '癒帶丸', 'Expel Dampness', 'Cure Discharge Pill'],
['Zhen Wu Tang', '真武湯', 'Expel Dampness', 'Black Turtle Decoction; True Warrior Decoction'],
['Zhi Zi Bai Pi Tang', '梔子栢皮湯', 'Expel Dampness', 'Gardenia and Phellodendron Decoction'],
['Zhong Man Fen Xiao Tang', '中滿分消湯', 'Expel Dampness', 'Separate and Reduce Fullness in the Middle Decoction'],
['Zhong Man Fen Xiao Wan', '中滿分消丸', 'Expel Dampness', 'Separate and Reduce Fullness in the Middle Pill'],
['Zhu Ling Tang', '豬苓湯', 'Expel Dampness', 'Polyporus Decoction'],
['Bu Dai Wan', '布袋丸', 'Expel Parasites', 'Cloth Sack Pill'],
['Dan Dao Qu Hui Tang', '膽道驅蛔湯', 'Expel Parasites', 'Drive Roundworms from the Biliary Tract Decoction'],
['Fei Er Wan', '肥兒丸', 'Expel Parasites', 'Fat Baby Pill'],
['Hua Chong Wan', '化蟲丸', 'Expel Parasites', 'Dissolve Parasites Pill'],
['Li Zhong An Hui Tang', '理中安蛔湯', 'Expel Parasites', 'Regulate the Middle and Calm Roundworms Decoction'],
['Lian Mei An Hui Tang', '蓮梅安蛔湯', 'Expel Parasites', 'Picrorhiza and Mume Decoction to Calm Roundworms'],
['Qu Tiao Tang', '驅條湯', 'Expel Parasites', 'Expel Tapeworms Decoction'],
['She Chuang Zi San', '蛇床子散', 'Expel Parasites', 'Cnidium Powder'],
['Wu Mei Wan', '鳥梅丸', 'Expel Parasites', 'Mume Pill'],
['Ban Xia Xie Xin Tang', '半夏瀉心湯', 'Harmonize', 'Pinellia Decoction to Drain the Epigastrium'],
['Chai Hu Da Yuan Yin', '柴胡達垣飲', 'Harmonize', 'Bupleurum Decotion to Reach the Membrane Source'],
['Chai Hu Gui Zhi Gan Jiang Tang', '柴胡桂枝乾薑湯', 'Harmonize', 'Bupleurum, Cinnamon Twig, and Ginger Decoction'],
['Chai Hu Gui Zhi Tang', '柴胡桂枝湯', 'Harmonize', 'Bupleurum and Cinnamon Twig Decoction'],
['Chai Hu Jia Mang Xiao Tang', '柴胡加硭硝湯', 'Harmonize', 'Bupleurum Decoction plus Mirabilite'],
['Chai Hu Qing Zao Tang', '柴胡清燥湯', 'Harmonize', 'Bupleurum Decoction to Clear Dryness'],
['Chai Hu Shu Gan San', '柴胡舒肝散', 'Harmonize', 'Bupleurum Powder to Spread the Liver'],
['Chai Hu Si Wu Tang', '柴胡四物湯', 'Harmonize', 'Bupleurum and Four Substance Decoction'],
['Chai Hu Zhi Jie Tang', '柴胡枳桔湯', 'Harmonize', 'Bupleurum, Bitter Orange, and Platycodon Decoction'],
['Chai Ping Tang', '柴平湯', 'Harmonize', 'Bupleurum and Calm the Stoamch Decoction'],
['Da Chai Hu Tang', '大柴胡湯', 'Harmonize', 'Major Bupleurum Decoction'],
['Da Yuan Yin', '達垣飲', 'Harmonize', 'Reach the Membrane Source Decoction'],
['Dan Huang Si Ni San', '丹黃四逆散', 'Harmonize', 'Moutan and Phellodendron Powder for Frigid Extemities'],
['Hao Qin Qing Dan Tang', '蒿芩清膽湯', 'Harmonize', 'Artemisia Annua and Scutellaria Decoction to Clear'],
['Hei Xiao Yao San', '黑逍遙散', 'Harmonize', 'Black Rambling Powder'],
['Hou Po Qi Wu Tang', '厚朴七物湯', 'Harmonize', 'Seven- Substance Decoction with Magnolia Bark'],
['Huang Lian Tang', '黃蓮湯', 'Harmonize', 'Coptis Decoction'],
['Jia Wei Xiao Yao San', '加味逍遙散', 'Harmonize', ' '],
['Jie Nue Qi Bao Yin', '截瘧七寶飲', 'Harmonize', 'Seven Treasures Decoction to Check Malarial Conditions'],
['Qing Pi Tang', '清脾湯', 'Harmonize', 'Clear the Spleen Decoction'],
['Qing Yi Tang', '清胰湯', 'Harmonize', 'Clear the Pancreas Decoction'],
['Sheng Jiang Xie Xin Tang', '生薑瀉心湯', 'Harmonize', 'Fresh Ginger Decoction to Drain the Epigastrium'],
['Shu Gan Li Pi Tang', '舒肝理脾湯', 'Harmonize', 'Spread the Liver and Regulate the Spleen Decoction'],
['Si Ni San', '四逆散', 'Harmonize', 'Frigid Extremities Power'],
['Tong Qi San', '通氣散', 'Harmonize', 'Unblock the Qi Powder'],
['Tong Xie Yao Fang', '痛瀉要方', 'Harmonize', 'Important Formula for Painful Diarrhea'],
['Xiao Chai Hu Tang', '小柴胡湯', 'Harmonize', 'Minor Bupleurum Decoction'],
['Xiao Yao San', '逍遙散', 'Harmonize', 'Rambling powder'],
['Yi Gan San', '抑肝散', 'Harmonize', 'Restrain the Liver Powder'],
['Cang Er Zi San', '蒼耳于散', 'Release the Exterior', 'Xanthium Powder'],
['Chai Ge Jie Ji Tang', '柴葛解肌湯', 'Release the Exterior', 'Bupleurum and Kudzu Decoction to Release the Muscle Layer Decoction'],
['Chuan Xiong Cha Tiao San', '川芎茶調散', 'Release the Exterior', 'Ligusticum Chuanxiong Powder to be Taken with Gree'],
['Cong Bai Jie Geng Tang', ' ', 'Release the Exterior', 'Scallion and Platycodon Decoction'],
['Cong Bai Qi Wei Yin', '葱白七味飲', 'Release the Exterior', 'Scallion Decoction with Seven Ingredients'],
['Cong Chi Tang', '葱豉湯', 'Release the Exterior', 'Scallion and Prepared Soybean Decoction'],
['Da Qiang Huo Tang', '大羌活湯', 'Release the Exterior', 'Major Notopterygium Decoction'],
['Da Qing Long Tang', '大青龍湯', 'Release the Exterior', 'Major Bluegreen Dragon Decoction'],
['Fang Feng Tong Sheng San', '防風通聖散', 'Release the Exterior', 'Ledebouriella Powder that Sagely Unblocks'],
['Ge Gen Huang Lian Huang Qin Tang', '葛根黃蓮黃苓湯', 'Release the Exterior', 'Kudzu Coptis and Scutellaria Decoction'],
['Ge Gen Jia Ban Xia Tang', ' ', 'Release the Exterior', 'Kudzu Decoction plus Pinellia'],
['Ge Gen Tang', '葛根湯', 'Release the Exterior', 'Kudzu Decoction'],
['Gui Zhi Er Yue Bi Yi Tang', ' ', 'Release the Exterior', 'Two Parts Cinnamon Twig Decoction and One Part Maidservant from Yue Decoction'],
['Gui Zhi Fu Zi Tang', ' ', 'Release the Exterior', 'Cinnamon Twig and Prepared Aconite Decoction'],
['Gui Zhi Jia Ge Gen Tang', ' ', 'Release the Exterior', 'Cinnamon Twig Decoction plus Kudzu'],
['Gui Zhi Jia Hou Po Xing Zi Tang', ' ', 'Release the Exterior', ' '],
['Gui Zhi Jia Shao Yao Tang', ' ', 'Release the Exterior', 'Cinnamon Twig Decoction plus Peony'],
['Gui Zhi Ma Huang Ge Ban Tang', ' ', 'Release the Exterior', 'Combined Cinnamon Twig and Ephedra Decoction'],
['Gui Zhi Qu Shao Yao Tang', ' ', 'Release the Exterior', 'Cinnamon Twig Decoction minus Peony'],
['Gui Zhi Tang', '桂枝湯', 'Release the Exterior', 'Cinnamon Twig Decoction'],
['Hua Gai San', ' ', 'Release the Exterior', 'Canopy Powder'],
['Huo Ren Cong Chi Tang', ' ', 'Release the Exterior', 'Scallion and Prepared Soybean Decoction from Book to Safeguard Life'],
['Jia Jian Wei Rui Tang', '加減葳蕤湯', 'Release the Exterior', 'Modiified Polygonatum Odoratum Decoction'],
['Jia Wei Xiang Su San', ' ', 'Release the Exterior', 'Augmented Cyperus and Perilla Leaf Powder'],
['Jing Fang Bai Du San', ' ', 'Release the Exterior', 'Schizonepeta & Ledebouriella Powder to Overcome Pathogenic Influences'],
['Jiu Wei Qiang Huo Tang Modified', ' ', 'Release the Exterior', 'Nine-Herb Decoction with Notopterygium from the Analytic Collection'],
['Jiu Wei Qiang Huo Tang', '九味羌活湯', 'Release the Exterior', 'Nine-herb Decoction with Notopterygium'],
['Ju Hua Cha Tiao San', ' ', 'Release the Exterior', 'Chrysanthemum Powder to be Taken with Green Tea'],
['Liu Wei Xiang Ru Yin', ' ', 'Release the Exterior', 'Six-Ingredient Decoction with Elsholtzia'],
['Ma Huang Fu Zi Gan Cao Tang', ' ', 'Release the Exterior', 'Ephedra, Prepared Aconite and Licorice Decoction'],
['Ma Huang Jia Zhu Tang', ' ', 'Release the Exterior', 'Ephedra Decoction plus Atractylodis'],
['Ma Huang Tang', '麻黃湯', 'Release the Exterior', 'Ephedra Decoction'],
['Ma Huang Xi Xin Fu Zi Tang', '麻黃細辛附子湯', 'Release the Exterior', 'Ephedra Asarum and Prepared Aconite Decoction'],
['Qiang Lan Tang', '羌藍湯', 'Release the Exterior', 'Notopterygium and Isatis Root Decoction'],
['Qu Feng Zhi Bao Dan', ' ', 'Release the Exterior', 'Greatest Treasure Special Pill to Dispel Wind'],
['Ren Shen Bai Du San', '入參敗毒散', 'Release the Exterior', 'Ginseng Power to Overcome Pathogenic Influences'],
['San Ao Tang', ' ', 'Release the Exterior', 'Three-Unbinding Decoction'],
['San Huang Shi Gao Tang', ' ', 'Release the Exterior', 'Three-Yellows and Gypsum Decoction'],
['Sang Ju Yin', '桑菊飲', 'Release the Exterior', 'Mulberry Leaf and Chrysanthemum Decoction'],
['She Gan Ma Huang Tang', ' ', 'Release the Exterior', 'Belamcanda and Ephedra Decoction'],
['Shen Su Yin', ' ', 'Release the Exterior', 'Ginseng and Perilla Leaf Decoction'],
['Sheng Ma Ge Gen Tang', '升麻葛根湯', 'Release the Exterior', 'Cimicifuga and Kudzu Decoction'],
['Shi Gao Tang', '石膏湯', 'Release the Exterior', 'Gypsum Decoction'],
['Shi Wei Xiang Ru Yin', ' ', 'Release the Exterior', 'Ten-Ingredient Decoction with Elsholtzia'],
['Wei Rui Tang', ' ', 'Release the Exterior', 'Polygonatum Odoratum Decoction'],
['Wu Ji San', '五積散', 'Release the Exterior', 'Five Accumulation Powder'],
['Wu Tou Gui Zhi Tang', ' ', 'Release the Exterior', 'Aconite and Cinnamon Twig Decoction'],
['Wu Wu Xiang Ru Yin', ' ', 'Release the Exterior', 'Five-Substance Decoction with Elsholtzia'],
['Xiang Ru San', '香薷散', 'Release the Exterior', 'Elsholtzia Powder'],
['Xiang Su Cong Chi Tang', ' ', 'Release the Exterior', 'Cyperus, Perilla Leaf, Scallion and Prepared Soybean Decoction'],
['Xiang Su San', '香蘇散', 'Release the Exterior', 'Cyperus and Perilla Leaf Power'],
['Xiao Qing Long Jia Shi Gao Tang', ' ', 'Release the Exterior', 'Minor Bluegreen Dragon Decoction plus Gypsum'],
['Xiao Qing Long Tang', '小青龍湯', 'Release the Exterior', 'Minor Blue-green Dragon Decoction'],
['Xin Yi San', ' ', 'Release the Exterior', 'Magnolia Flower Powder'],
['Xuan Du Fa Biao Tang', ' ', 'Release the Exterior', 'Dissipate Toxin and Release Exterior Decoction'],
['Yi Wu Chai Ge Jie Ji Tang', ' ', 'Release the Exterior', 'Bupleurum and Kudzu Decoction To Release the Muscle Layer'],
['Yin Qiao Bai Du San', ' ', 'Release the Exterior', 'Honeysuckle and Forsythia Powder to Overcome Pathogenic Influences'],
['Yin Qiao San', '銀翹散', 'Release the Exterior', 'Honeysuckle and Forsythia powder'],
['Yin Qiao Tang', ' ', 'Release the Exterior', 'Honeysuckle and Forsythia Decoction'],
['Zai Zao San', '再造散', 'Release the Exterior', 'Renewal Powder'],
['Xiang Fu Xuan Fu Hua Tang', '香附旋覆花湯', 'Transform Phlegm', 'Cyperus and Inula Decoction'],
['Ban Xia Bai Zhu Tian Ma Tang', '半夏白朮天麻湯', 'Transform Phlegm', 'Pinellia Atractylodis Macrocephalae and Gastrodi'],
['Bei Mu Gua Lou San', '貝母瓜蔞散', 'Transform Phlegm', 'Fritillaria and Trichosanthea Fruit Powder'],
['Chai Hu Xian Xiong Tang', '柴胡陷胸湯', 'Transform Phlegm', 'Bupleurum Decoction for Sinking Into the Chest'],
['Dao Tan Tang', '導痰湯', 'Transform Phlegm', 'Guide Out Phlegm Decoction'],
['Ding Xian Wan', '定涎丸', 'Transform Phlegm', 'Arrest Seizures Pill'],
['Er Chen Tang', '二陳湯', 'Transform Phlegm', 'Two Cured Decoction'],
['Er Mu San', ' ', 'Transform Phlegm', 'Fritillaria and Anemarrhena Powder'],
['Gan Cao Gan Jiang Fu Ling Bai Zhu Tang', '甘草乾薑茯苓白朮湯', 'Transform Phlegm', 'Licorice, Ginger, Poria and Atractylodis Macrocephalae Decoction'],
['Gua Di San', '瓜蒂散', 'Transform Phlegm', 'Melon Pedicle Powder'],
['Gua Lou Zhi Shi Tang', '瓜蔞枳實湯', 'Transform Phlegm', 'Trichosanthes Fruit and Immature Bitter Orange Decoction'],
['Gui Ling Wu Wei Gan Cao Tang', '桂苓五味甘草湯', 'Transform Phlegm', 'Cinnamon Twig, Poria, Schisandra and Licorice Decoction'],
['Hai Zao Yu Hu Tang', '海藻玉壺湯', 'Transform Phlegm', 'Sargassum Decoction for the Jade Flask'],
['Huang Lian Wen Dan Tang', ' ', 'Transform Phlegm', 'Coptis Decoction to Warm the Gallbladder'],
['Jia Wei Er Chen Tang', '加味二陳湯', 'Transform Phlegm', 'Augmented Two-Cured Decoction'],
['Jin Shui Liu Jun Jian', '金水六君煎', 'Transform Phlegm', 'Six-Gentleman of Metal and Water Decoction'],
['Ling Gan Wu Wei Jiang Xin Tang', '苓甘五味薑辛湯', 'Transform Phlegm', 'Poria, Licorice, Schisandra, Ginger and Asarum Decoction'],
['Ling Gui Zhu Gan Tang', '苓桂朮甘湯', 'Transform Phlegm', 'Poria, Cinnamon Twig, Atractylodis Macrocephalae, and Licorice Decoction'],
['Liu An Jian', '六安煎', 'Transform Phlegm', 'Six Serenity Decoction'],
['Qing Qi Hua Tan Wan', '清氣化痰丸', 'Transform Phlegm', 'Clear the Qi and Transform Phlegm Pill'],
['Qing Shi Hua Tan Tang', '清濕化痰湯', 'Transform Phlegm', 'Clear Dampness and Transform Phlegm Decoction'],
['San Sheng San', '三聖湯', 'Transform Phlegm', 'Three-Sage Powder'],
['San Zi Yang Qin Tang', '三子養親湯', 'Transform Phlegm', 'Three-Seed Decoction to Nourish One\'s Parents'],
['Shi Wei Wen Dan Tang', '十味溫膽湯', 'Transform Phlegm', 'Ten-Ingredient Decoction to Warm the Gallbladder'],
['Shi Yi Wei Wen Dan Tang', '十一味溫膽湯', 'Transform Phlegm', 'Eleven-Ingredient Decoction to Warm the Gallbladder'],
['Wen Dan Tang', '溫膽湯', 'Transform Phlegm', 'Warm the Gallbladder Decoction'],
['Xia Ku Cao Gao', '夏枯草膏', 'Transform Phlegm', 'Prunella Syrup'],
['Xiao Luo Wan', ' ', 'Transform Phlegm', 'Reduce Scrofula Pill'],
['Xian Luo Wan', '消瘰丸', 'Transform Phlegm', 'Reduce Scrofula Pill'],
['Xiao Xian Xiong Tang', '小陷胸湯', 'Transform Phlegm', 'Minor Sinking into the Chest Decoction'],
['Zhi Sou San', '止嗽散', 'Transform Phlegm', 'Stop coughing Powder']]

