require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Clinic::VisitsController do

  # This should return the minimal set of attributes required to create a valid
  # Clinic::Visit. As you add validations to Clinic::Visit, be sure to
  # adjust the attributes here as well.
  let(:patient) {create :clinic_patient}
  let(:valid_attributes) { { "patient_id" => patient.id } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Clinic::VisitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all clinic_visits as @clinic_visits" do
      visit = Clinic::Visit.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:clinic_visits)).to eq([visit])
    end
  end

  describe "GET show" do
    it "assigns the requested clinic_visit as @clinic_visit" do
      visit = Clinic::Visit.create! valid_attributes
      get :show, {:id => visit.to_param}, valid_session
      expect(assigns(:clinic_visit)).to eq(visit)
    end
  end

  describe "GET new" do
    it "assigns a new clinic_visit as @clinic_visit" do
      get :new, {}, valid_session
      expect(assigns(:clinic_visit)).to be_a_new(Clinic::Visit)
    end
  end

  describe "GET edit" do
    it "assigns the requested clinic_visit as @clinic_visit" do
      visit = Clinic::Visit.create! valid_attributes
      get :edit, {:id => visit.to_param}, valid_session
      expect(assigns(:clinic_visit)).to eq(visit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Clinic::Visit" do
        expect {
          post :create, {:clinic_visit => valid_attributes}, valid_session
        }.to change(Clinic::Visit, :count).by(1)
      end

      it "assigns a newly created clinic_visit as @clinic_visit" do
        post :create, {:clinic_visit => valid_attributes}, valid_session
        expect(assigns(:clinic_visit)).to be_a(Clinic::Visit)
        expect(assigns(:clinic_visit)).to be_persisted
      end

      it "redirects to the created clinic_visit" do
        post :create, {:clinic_visit => valid_attributes}, valid_session
        expect(response).to redirect_to(Clinic::Visit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved clinic_visit as @clinic_visit" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Clinic::Visit).to receive(:save).and_return(false)
        post :create, {:clinic_visit => { "patient_id" => "invalid value" }}, valid_session
        expect(assigns(:clinic_visit)).to be_a_new(Clinic::Visit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Clinic::Visit).to receive(:save).and_return(false)
        post :create, {:clinic_visit => { "patient_id" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested clinic_visit" do
        visit = Clinic::Visit.create! valid_attributes
        # Assuming there are no other clinic_visits in the database, this
        # specifies that the Clinic::Visit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Clinic::Visit).to receive(:update).with({ "patient_id" => "" })
        put :update, {:id => visit.to_param, :clinic_visit => { "patient_id" => "" }}, valid_session
      end

      it "assigns the requested clinic_visit as @clinic_visit" do
        visit = Clinic::Visit.create! valid_attributes
        put :update, {:id => visit.to_param, :clinic_visit => valid_attributes}, valid_session
        expect(assigns(:clinic_visit)).to eq(visit)
      end

      it "redirects to the clinic_visit" do
        visit = Clinic::Visit.create! valid_attributes
        put :update, {:id => visit.to_param, :clinic_visit => valid_attributes}, valid_session
        expect(response).to redirect_to(visit)
      end
    end

    describe "with invalid params" do
      it "assigns the clinic_visit as @clinic_visit" do
        visit = Clinic::Visit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Clinic::Visit).to receive(:save).and_return(false)
        put :update, {:id => visit.to_param, :clinic_visit => { "patient_id" => "invalid value" }}, valid_session
        expect(assigns(:clinic_visit)).to eq(visit)
      end

      it "re-renders the 'edit' template" do
        visit = Clinic::Visit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Clinic::Visit).to receive(:save).and_return(false)
        put :update, {:id => visit.to_param, :clinic_visit => { "patient_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested clinic_visit" do
      visit = Clinic::Visit.create! valid_attributes
      expect {
        delete :destroy, {:id => visit.to_param}, valid_session
      }.to change(Clinic::Visit, :count).by(-1)
    end

    it "redirects to the clinic_visits list" do
      visit = Clinic::Visit.create! valid_attributes
      delete :destroy, {:id => visit.to_param}, valid_session
      expect(response).to redirect_to(clinic_visits_url)
    end
  end

end
