require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Diagnosis::PatternSymptomsController do

  # This should return the minimal set of attributes required to create a valid
  # Diagnosis::PatternSymptom. As you add validations to Diagnosis::PatternSymptom, be sure to
  # adjust the attributes here as well.
  let(:pattern) {create :diagnosis_pattern}
  let(:valid_attributes) { { "pattern_id" => pattern.id } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Diagnosis::PatternSymptomsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all diagnosis_pattern_symptoms as @diagnosis_pattern_symptoms" do
      pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:diagnosis_pattern_symptoms)).to eq([pattern_symptom])
    end
  end

  describe "GET show" do
    it "assigns the requested diagnosis_pattern_symptom as @diagnosis_pattern_symptom" do
      pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
      get :show, {:id => pattern_symptom.to_param}, valid_session
      expect(assigns(:diagnosis_pattern_symptom)).to eq(pattern_symptom)
    end
  end

  describe "GET new" do
    it "assigns a new diagnosis_pattern_symptom as @diagnosis_pattern_symptom" do
      get :new, {}, valid_session
      expect(assigns(:diagnosis_pattern_symptom)).to be_a_new(Diagnosis::PatternSymptom)
    end
  end

  describe "GET edit" do
    it "assigns the requested diagnosis_pattern_symptom as @diagnosis_pattern_symptom" do
      pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
      get :edit, {:id => pattern_symptom.to_param}, valid_session
      expect(assigns(:diagnosis_pattern_symptom)).to eq(pattern_symptom)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Diagnosis::PatternSymptom" do
        expect {
          post :create, {:diagnosis_pattern_symptom => valid_attributes}, valid_session
        }.to change(Diagnosis::PatternSymptom, :count).by(1)
      end

      it "assigns a newly created diagnosis_pattern_symptom as @diagnosis_pattern_symptom" do
        post :create, {:diagnosis_pattern_symptom => valid_attributes}, valid_session
        expect(assigns(:diagnosis_pattern_symptom)).to be_a(Diagnosis::PatternSymptom)
        expect(assigns(:diagnosis_pattern_symptom)).to be_persisted
      end

      it "redirects to the created diagnosis_pattern_symptom" do
        post :create, {:diagnosis_pattern_symptom => valid_attributes}, valid_session
        expect(response).to redirect_to(Diagnosis::PatternSymptom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diagnosis_pattern_symptom as @diagnosis_pattern_symptom" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Diagnosis::PatternSymptom).to receive(:save).and_return(false)
        post :create, {:diagnosis_pattern_symptom => { "pattern_id" => "invalid value" }}, valid_session
        expect(assigns(:diagnosis_pattern_symptom)).to be_a_new(Diagnosis::PatternSymptom)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Diagnosis::PatternSymptom).to receive(:save).and_return(false)
        post :create, {:diagnosis_pattern_symptom => { "pattern_id" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diagnosis_pattern_symptom" do
        pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
        # Assuming there are no other diagnosis_pattern_symptoms in the database, this
        # specifies that the Diagnosis::PatternSymptom created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Diagnosis::PatternSymptom).to receive(:update).with({ "pattern_id" => "" })
        put :update, {:id => pattern_symptom.to_param, :diagnosis_pattern_symptom => { "pattern_id" => "" }}, valid_session
      end

      it "assigns the requested diagnosis_pattern_symptom as @diagnosis_pattern_symptom" do
        pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
        put :update, {:id => pattern_symptom.to_param, :diagnosis_pattern_symptom => valid_attributes}, valid_session
        expect(assigns(:diagnosis_pattern_symptom)).to eq(pattern_symptom)
      end

      it "redirects to the diagnosis_pattern_symptom" do
        pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
        put :update, {:id => pattern_symptom.to_param, :diagnosis_pattern_symptom => valid_attributes}, valid_session
        expect(response).to redirect_to(pattern_symptom)
      end
    end

    describe "with invalid params" do
      it "assigns the diagnosis_pattern_symptom as @diagnosis_pattern_symptom" do
        pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Diagnosis::PatternSymptom).to receive(:save).and_return(false)
        put :update, {:id => pattern_symptom.to_param, :diagnosis_pattern_symptom => { "pattern_id" => "invalid value" }}, valid_session
        expect(assigns(:diagnosis_pattern_symptom)).to eq(pattern_symptom)
      end

      it "re-renders the 'edit' template" do
        pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Diagnosis::PatternSymptom).to receive(:save).and_return(false)
        put :update, {:id => pattern_symptom.to_param, :diagnosis_pattern_symptom => { "pattern_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diagnosis_pattern_symptom" do
      pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
      expect {
        delete :destroy, {:id => pattern_symptom.to_param}, valid_session
      }.to change(Diagnosis::PatternSymptom, :count).by(-1)
    end

    it "redirects to the diagnosis_pattern_symptoms list" do
      pattern_symptom = Diagnosis::PatternSymptom.create! valid_attributes
      delete :destroy, {:id => pattern_symptom.to_param}, valid_session
      expect(response).to redirect_to(diagnosis_pattern_symptoms_url)
    end
  end

end
